# Generated by Django 4.1.7 on 2023-03-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_category_rename_title_gif_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
