# Generated by Django 4.1.7 on 2023-03-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_additions_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addition', to='posts.post'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.ManyToManyField(related_name='categories', to='posts.post')),
            ],
        ),
    ]
